SELECT * from member;



CREATE TABLE member
(
    id number(5) PRIMARY KEY,
    name varchar2(10)
);

CREATE TABLE member
(
    id number(5) GENERATED BY DEFAULT AS IDENTITY,
    name varchar2(10),
    PRIMARY KEY (id)
);